version: '3'

services:
  wpkgup:
    image: wpkg/wpkgup
    container_name: wpkgup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080/tcp
    volumes:
      - ./data:/app/data