name: Release

on:
  push:
    tags:
      - 'v**'

jobs:
  build:
    name: Build & Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag name
        id: tag_name
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'

      - name: Download WpkgUp to upload
        run: curl https://cdn.wpkg.dev/api/wpkgup/stable/linux/arm64/latest/getbinary -o wpkgup-uploader

      - name: Build for Linux x64
        run: |
          GOOS=linux GOARCH=amd64 VERSION=${{ steps.tag_name.outputs.version }} make build
          mv wpkgup wpkgup-linux-x64

      - name: Build for Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 VERSION=${{ steps.tag_name.outputs.version }} make build
          mv wpkgup wpkgup-linux-arm64

      - name: Build for Windows x64
        run: |
          GOOS=windows GOARCH=arm64 VERSION=${{ steps.tag_name.outputs.version }} make build
          mv wpkgup.exe wpkgup-windows-x64.exe

      - name: Upload for Linux x64
        run: |
          mv wpkgup-linux-x64 wpkgup
          ./wpkgup-uploader upload-binary wpkgup stable linux x64 ${{ steps.tag_name.outputs.version }} wpkgup -k ${{ secrets.WPKGUP_KEY }}
          rm wpkgup

      - name: Upload for Linux ARM64
        run: |
          mv wpkgup-linux-arm64 wpkgup
          ./wpkgup-uploader upload-binary wpkgup stable linux arm64 ${{ steps.tag_name.outputs.version }} wpkgup -k ${{ secrets.WPKGUP_KEY }}
          rm wpkgup

      - name: Upload for Windows x64
        run: |
          mv wpkgup-windows-x64.exe wpkgup.exe
          ./wpkgup-uploader upload-binary wpkgup stable linux x64 ${{ steps.tag_name.outputs.version }} wpkgup.exe -k ${{ secrets.WPKGUP_KEY }}
          rm wpkgup.exe

      - name: Upload release files
        uses: https://gitea.com/actions/release-action@main
        with:
          api_key: '${{secrets.RELEASE_TOKEN}}'
          draft: true
          body: |
            <!-- Write summary here -->
            ---
            ## Features
            ## Changes
            ## Bug Fixes
            ## Internal Changes
          # files: |
          #   ./wpkgup